### ISSUE TITLE
Маркер формата API

### ISSUE THREAD

**Issue by denis96z** [gothing/draft#11]
*Кейс:*
Иногда при описании возникает необходимость классифицировать API в зависимости, например, от формата ответа. Допустим, в API в версии v1 body имеет вид:
```
{"status":200,"user_id":1234}
```
а в версии v2:
```
{"status":"ok","body":{"user_id":1234}}
```

Хочется иметь возможность указать это в интерфейсе, передавая дополнительный параметр в схеме, например
format=NEW, format=OLD
так чтобы это поле отображалось например в блоке title

**Comment by RubaXa** [comment]
Я подумаю как это лучше сделать.

**Comment by RubaXa** [comment]
@denis96z короче, я думаю надо это забыть, как страшный сон, разные схемы ответа, это прям нужно брать и писать версию v2 фронта, а это тумач для нас.
