### ISSUE TITLE
Маркер Graceful Degradation для полей ответа

### ISSUE THREAD

**Issue by denis96z** [gothing/draft#14]
*Кейс:*
Некоторые поля ответа, которые по факту являются обязательными, мы не можем вернуть в случае частичного отказа системы.

*Предлагаемое решение:*
Хотелось бы иметь отдельный маркер, который позволил бы считать эти поля обязательными, но при этом пометить поля как возможно отсутствующие в случае отказа.

**Comment by RubaXa** [comment]
Это как? 200 но без ответа? По моему это какое-то плохое АПИ/Демон, с таким успехом можно прийти ещё не только к пустым полям, но их их формату, мол если вместо строки число, то это плохой ответ, вы уж там следите.

Так не должно быть, если описано поле, значит оно должно быть в ответе, если его нет, но такой ответ есть, значит такой вариант должен быть задокументирован отдельно.

Не?

**Comment by denis96z** [comment]
Не совсем. Речь идет о том что у API может быть основное целевое действие и побочное, при этом побочное может быть блокирующим (необходимо выполнить откат внесенных изменений и вернуть ошибку) и неблокирующим (обработка вызова API может быть продолжена с определенными ограничениями). Конкретный кейс: есть API которое удаляет все сессии пользователя (основное действие) и выдает одноразовый токен по которому клиент может создать новую сессию (неблокирующее побочное действие). В случае если основное действие выполнено (сессии удалены), клиент должен быть уведомлен о том что действие завершено успешно, однако хранилище с токенами недоступно и новый токен выдан быть не может, однако это не является блокирующей ошибкой для клиента, она может быть обработана тем способом который подходит для конкретного клиента, без навязывания этой логики сервером, в этом случае поле с токеном в ответе будет отсутствовать (при этом формат поля меняться не будет никогда). Конечно можно считать это поле опциональным, но это не совсем так, это поле опционально только в одном конкретном случае - при частичном отказе системы, хотелось бы иметь что-то вроде метки которая привлекает внимание к этому факту.

**Comment by RubaXa** [comment]
Пока это выглядит как просто два варианта работы апи, не варианта ответа, а именно работы.

> Конкретный кейс: есть API которое удаляет все сессии пользователя (основное действие) и выдает одноразовый токен по которому клиент может создать новую сессию (неблокирующее побочное действие)

Вот это ваще странное АПИ :] Сейчас получается, что API отвечает рандомно и не понятно, что делать, если мне нужен этот токен?

**Comment by denis96z** [comment]
> Сейчас получается, что API отвечает рандомно и не понятно, что делать, если мне нужен этот токен?

API "прилагает максимальные усилия" чтобы вернуть полный ответ, в случае если это невозможно API возвращает частичный ответ, клиент вправе обработать этот ответ так как нужно именно этому клиенту, может отобразить ошибку а может "сделать вид" что так и задумано, или действовать в зависимости от конкретного кейса, смысл в том чтобы логику обработки данного сбоя не выносить на сервер.



> Пока это выглядит как просто два варианта работы апи

Да, это именно так и есть. А от доки хочется просто универсального способа отображения этого, без необходимости явно указывать это в описании: краткого и привлекающего внимание.
