### ISSUE TITLE
Маркер deprecated для параметра

### ISSUE THREAD

**Issue by denis96z** [gothing/draft#15]
**Кейс:**
Некоторые параметры могут быть нерекомендованы к использованию, например, было два раздельных параметра email&phone, их заменили на один комбинированный - login, при этом при для новых клиентов предпочтительнее использование именно login, однако не хотелось бы вводить в заблуждение разработчиков обращающихся к документации для поддержания старых клиентов, поскольку использование старых параметров все еще допускается.

**Предлагаемое решение:**
Добавить возможность отметить параметр как устаревший.

**P.S.** Это поддерживается в swagger:
https://swagger.io/specification/#parameter-object

**Comment by RubaXa** [comment]
Давай делать это через тег `deprecated`?

**Comment by denis96z** [comment]
> Давай делать это через тег `deprecated`?

Выглядит удобно
