### ISSUE TITLE
Маркер optional для полей ответа

### ISSUE THREAD

**Issue by denis96z** [gothing/draft#18]
**Кейс:**
Хочется некоторое поле ответа пометить как опциональное прям в доке, т. е. если в теге json есть omitempty то отображать на фронте например "optional" в комментарии к полю

**Comment by RubaXa** [comment]
Маркер тут не получится, т.к. это JSON с коментами, но можно указать, что поле может быть `undefined`:

![image](https://user-images.githubusercontent.com/1109562/109660442-eea54580-7b79-11eb-9874-f7d8a5a5b9ed.png)
