### ISSUE TITLE
Зачинить парсинг json тегов

### ISSUE THREAD

**Issue by reo7sp** [gothing/draft#2]
**Как воспроизвести:**
Задать такую структуру:
```go
type Response struct {
        // ...
	RedirectURL string `json:"redirect_to,omitempty"`
}
```

**Получил:**
<img width="824" alt="Screenshot 2020-08-04 at 13 56 08" src="https://user-images.githubusercontent.com/1623280/89286141-5b934400-d65a-11ea-9147-72d2c0d21cf6.png">

**Ожидал:**
<img width="784" alt="Screenshot 2020-08-04 at 13 56 23" src="https://user-images.githubusercontent.com/1623280/89286153-6057f800-d65a-11ea-9799-acd35fc7463c.png">

**Comment by reo7sp** [comment]
MR: https://github.com/gothing/draft/pull/3

**Comment by RubaXa** [comment]
@reo7sp https://github.com/gothing/draft/releases/tag/v1.0.0-alpha.9 🎉
